baseURL = "https://callumgwtaylor.github.io/blog/"
languageCode = "en-us"
title = "CallumGWTaylor"
theme = "cactus"
publishDir = "docs"
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true
[params]
  showAllPostsOnHomePage = true


